// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODOLOQUEPUEDASCOMER.Data;

#nullable disable

namespace TODOLOQUEPUEDASCOMER.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240205153020_MenuDbExaul")]
    partial class MenuDbExaul
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TODOLOQUEPUEDASCOMER.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bebidas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platillo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bebidas = "Jugo de naranja",
                            Platillo = "Salmón a la plancha con arroz y espárragos",
                            Precio = "5 $"
                        },
                        new
                        {
                            Id = 2,
                            Bebidas = "Chai",
                            Platillo = "Anguila teriyaki con sésamo",
                            Precio = "5 $"
                        },
                        new
                        {
                            Id = 3,
                            Bebidas = "Coca Cola ",
                            Platillo = "Solomillo de cordero al horno con costra verde y chalotas",
                            Precio = "5 $"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
